name: B3 trading signals bot

on:
  schedule:
    - cron: "15 21 * * 1-5" # runs at 21:15 UTC, Monday-Friday
    #- cron: "45 21 * * 1-5" # runs at 21:45 UTC, Monday-Friday
    #- cron: "15 22 * * 1-5" # runs at 22:15 UTC, Monday-Friday
  workflow_dispatch:        # runs manualy if desired

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run flag cache
        uses: actions/cache@v4
        with:
          path: state
          key: run-flag-${{ runner.os }}

      - name: Check if executed
        id: flagcheck
        run: |
          TODAY=$(date +"%Y-%m-%d")
          mkdir -p state
          LAST=$(cat state/run_flag.txt 2>/dev/null || echo "none")

          echo "Today: $TODAY"
          echo "Last run: $LAST"

          if [ "$LAST" = "$TODAY" ]; then
            echo "already_ran=true" >> $GITHUB_OUTPUT
          else
            echo "already_ran=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip if executed
        if: steps.flagcheck.outputs.already_ran == 'true'
        run: |
          echo "Execution already done. Skipping."
          exit 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          for i in {1..3}; do
          echo "Attempt $i of 3."
            python b3_trading_signals_bot.py && break || echo "Attempt $i has failed. Retrying in 30 seconds." && sleep 30
          done

      - name: Mark execution
        if: success()
        run: |
          date +"%Y-%m-%d" > state/run_flag.txt
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: data/report/report.xlsx

      - name: Save run flag cache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: state
          key: run-flag-${{ runner.os }}
